env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    gh_token: "ENCRYPTED[dc0644a77c6d3db2d67ac989b12de0b8a7016fe5a30a71ec53a514f6c6dc5fd776ede263167225ad8c3c186c3fb0eb48]"
    bot_api: "ENCRYPTED[!1c09f593c42a7116bef7541ae720b7c7457b236b90ba1b1e24d61562b33e62d2eceaa79fd29047c4224f11100fd3916f!]"
    chat_id: "ENCRYPTED[d68d71a47ad814b5ff2f0db18961fd0bbfdc9aad64bec8d7630b25b50f306a86a165a2a27b2d53fa889020c8036fa6a9]"
    rom: "xdroid"
  
task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - bash build system gh
    upload_ccache_script: # Upload ccache to cloud foreground
      - bash upload_ccache gh # Ccache uploading script
