#!/bin/bash
cd /tmp/rom # Depends on where source got synced

#include function script
. /tmp/ci/function

SECONDS=0

# Normal build steps
. build/envsetup.sh
lunch $lunch
export _JAVA_OPTIONS="-Xmx10g"
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 15G
ccache -o compression=true
ccache -z

# compile plox
bash -c $compile_plox &
sleep 75m
tg "Stop Compiling Rom To Collect Cache
Status: $status | Build No: $build_no"
kill %1

if [ ! -e out/target/product/$device/*$device*2022*zip ]; then
send_zip=$(up out/target/product/$device/*$device*2022*zip) && tg $id "Build Succeed!
$send_zip"
fi
ccache -s # Let's print ccache statistics finally