#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

# include function script
. /tmp/ci/function

install_apt

SECONDS=0

cd /tmp # Where to download cccahe

# Download ccahe
download_ccache
tg "Cache was Downloaded Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $status | Build No: $build_no"

# Extract ccache so ci can use it
echo " Extracting CCACHE "
if [ -e $rom/*.zip.* ]; then
mv $rom/*.zip.* /tmp
7za x *.zip.001
time tar xf *.tar.gz
fi

# Remove unnecessary downloaded file
rm -rf *.tar.gz
rm -rf *.zip.*

# fix
echo "" > /etc/mtab