#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

#include function script
. /tmp/ci/function

# set your gmail and email
git config --global user.name "$username"
git config --global user.email "$gmail"

SECONDS=0

# Sync with repo init command, -device,-mips,-darwin,-notdefault to save time and storage
repo init --depth=1 --no-repo-verify -u $android_manifest -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# Clone local manifest!
bash -c "$local_manifest"

tg "Cloned all Sources Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $status | Build No: $build_no"
