#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

tg () {
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$1&chat_id=${chat_id}"
}

SECONDS=0

##some of my work
git config --global user.name "reiyuura"
git config --global user.email "yuiireichi@gmail.com"

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u https://github.com/xdroid-oss/xd_manifest -b twelve -g default,-mips,-darwin,-notdefault

# Local manifest
# git clone https://github.com/reiyuura/local_manifest --depth=1 -b xdroid .repo/local_manifest

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
git clone https://github.com/reiyuura/android_device_xiaomi_vince -b xd-test device/xiaomi/vince
git clone --depth=1 https://github.com/reiyuura/android_vendor_xiaomi_vince -b master vendor/xiaomi/vince
git clone --depth=1 https://github.com/GhostMaster69-dev/android_kernel_xiaomi_vince -b 12 kernel/xiaomi/vince
git clone -b master --depth=1 https://gitlab.com/GhostMaster69-dev/cosmic-clang prebuilts/clang/host/linux-x86/clang-cosmic

tg "Cloned all Sources Successfully! Time Took: $(($SECONDS / 60))min and $(($SECONDS % 60))sec "
